### PR TITLE
Update elyra notebook image to v0.0.8

### PR DESCRIPTION
**Pull request by akchinSTC**
Bumps Elyra to version 2.2.4
Change log:
https://github.com/elyra-ai/elyra/blob/master/docs/source/getting_started/changelog.md

### CODE REVIEW

**Comment by anishasthana** [comment]
cc @harshad16

**Review by harshad16 — COMMENTED** [review]
/lgtm
Thanks @akchinSTC  for the update here :100:

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
