### PR TITLE
Update Prometheus Object

### PR DESCRIPTION
**Pull request by anishasthana**
1. Increase number of prometheus replicas for HA
2. Update Prometheus labels

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Comment by crobby** [comment]
Any chance that the prometheus tests would be affected by this change?

**Comment by anishasthana** [comment]
@crobby That's possible. Let me take a look

**Comment by anishasthana** [comment]
Closing in favour of #349

**Pull request closed without merging**
