### PR TITLE
Change Update strategy for NB deployments

### PR DESCRIPTION
**Pull request by VaishnaviHire**
This PR updates manifests from PR - https://github.com/opendatahub-io/kubeflow/pull/98
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
/approve

thanks :+1:

**Review by atheo89 — COMMENTED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
@VannTen Can you review this one ? Its just adding the changes from your PR to the release

**Review by harshad16 — APPROVED** [review]
/lgtm 
thanks :+1:

**Review by harshad16 — APPROVED** [review]
/lgtm 
thanks :+1:

**Comment by VaishnaviHire** [comment]
Adding lgtm, since I just rebased

/lgtm

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Pull request merged**
