### PR TITLE
Update for ODH Dashboard v2.8.0 release

### PR DESCRIPTION
**Pull request by andrewballantyne**
Dashboard Release Notes: 
- https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.7.0
- https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.8.0

Dashboard release steps are being tested with this PR. I followed no6 in the [release steps](https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/releases.md#release-steps). @LaVLaS let me know if we didn't quite get the right steps in place here.

### CODE REVIEW

**Comment by LaVLaS** [comment]
@andrewballantyne There is one item missing that I forgot to add to the odh-dashboard release docs and that is restoring the OWNERS file to the odh-dashboard repo. https://github.com/opendatahub-io/odh-dashboard/pull/972

**Comment by LaVLaS** [comment]
It looks like the CI test is [failing](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_odh-manifests/734/pull-ci-opendatahub-io-odh-manifests-master-odh-manifests-e2e/1626664830423273472#1:build-log.txt%3A685) due to a change in the xpath for the `jupyter` ODHApplication tile

It looks like you need to change the xpath on [line 81](https://github.com/opendatahub-io/odh-manifests/blob/master/tests/resources/ods-ci/test-odh-dashboard-jupyterlab-notebook.robot#L81) of the ods-ci testcase to 
```
//div[contains(@class,"pf-c-card") and @data-id="jupyter"]/div[contains(@class,"pf-c-card__footer")]/a
```

**Comment by andrewballantyne** [comment]
@LaVLaS can you help me understand how to read this error the e2e test found? I skimmed looking for it and all I see is "container exited with code 1, reason Error" haha -- clearly an error happened... what error?

**Comment by LaVLaS** [comment]
> @LaVLaS can you help me understand how to read this error the e2e test found? I skimmed looking for it and all I see is "container exited with code 1, reason Error" haha -- clearly an error happened... what error?

After digging into the problem, this might require a bump of the [ods-ci ](https://github.com/red-hat-data-services/ods-ci) release version. I think the failure is due to the fact that we are using `1.20.0` release of their automation and need to update the version

**Comment by andrewballantyne** [comment]
Dashboard went through another cycle -- we are not on v2.8.0

@LaVLaS I am thinking the action item here is on you -- if you're thinking it is on me, then we are probably in deadlock 😄 Let me know what you think the next action here is.

**Comment by LaVLaS** [comment]
@andrewballantyne Following up, this [PR #1](https://github.com/andrewballantyne/odh-manifests/pull/1) to your fork for this PR branch should unblock the CI tests failure in the ods-ci test execution

**Pull request merged**
