### PR TITLE
Use secret param in JH DB for postgres pass

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by vpavlin** [comment]
@nakfour Can you please take a look? This is the PR for "parameterizing" the JH DB password

**Comment by nakfour** [comment]
@vpavlin for the secret, does it need to contain these exactly the same as the default secret, or can users change it. We need to add text in the readme to describe this
```PROMETHEUS_API_TOKEN: 
  CONFIGPROXY_AUTH_TOKEN: 
  JPY_COOKIE_SECRET: 
  JUPYTERHUB_CRYPT_KEY: 
```

**Comment by vpavlin** [comment]
Those would in ideal case change for each ODH deployment - so yes, user can change those values

**Comment by vpavlin** [comment]
FYI @wseaton

**Comment by vpavlin** [comment]
> We need to add text in the readme to describe this

But that is not part of this PR, so I would rather do it in a separate one to avoid a CI re-run

**Comment by wseaton** [comment]
@vpavlin this looks good, basically how I am doing it in my deployment. +1 to adding the other variables that need to be set each deployment as well in a different PR.

**Comment by vpavlin** [comment]
As part of this PR I am also removing the POSTGRESQL_USER config because it was not used anyway and could cause issues if someone tried to change it. User is now hardcoded to `jupyterhub`

**Review by nakfour — APPROVED** [review]

**Comment by vpavlin** [comment]
@crobby @anishasthana Prometheus seems to be failing in the tests..can someone investigate? I am out for the rest of the week:(

**Comment by crobby** [comment]
A fair chance this needs a rebase after Anish's change got merged yesterday

**Comment by crobby** [comment]
Trying a rebase in https://github.com/opendatahub-io/odh-manifests/pull/362

**Comment by anishasthana** [comment]
The tests passed in #362 . Looks like a rebase was all that was needed.

**Comment by crobby** [comment]
@vpavlin  If you want to rebase this change, I can close #362 or we can just lg-tm that and run.  Either way is fine with me.  Let me know though since we'd like to get these in for the 1.0.7 version.

**Comment by LaVLaS** [comment]
Closing this since the changes were rebased on the latest `master` in #362 by @crobby

**Pull request closed without merging**
