### PR TITLE
Increase Dashboard Replicas to 5

### LINKED ISSUE #676: Add Replicas to Dashboard Deployment
**Is your feature request related to a problem? Please describe.**
High number of concurrent users cause throttling in Dashboard pods. 

**Describe the solution you'd like**
Increase Dashboard deployment replicas to 5

### PR DESCRIPTION
**Pull request by VaishnaviHire**
Fixes #676 

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by cfchase — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
Did you test this with the latest build of odh-dasbhoard release since that setting is still `replicas: 2`

https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/deployment.yaml#L6

**Comment by VaishnaviHire** [comment]
> Did you test this with the latest build of odh-dasbhoard release since that setting is still `replicas: 2`
> 
> https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/base/deployment.yaml#6

No, should this PR be opened in the `odh-dashboard` instead?

**Comment by VaishnaviHire** [comment]
Moving this PR to `odh-dashboard` , to be tested with latest Dashboard release

**Pull request closed without merging**
