### PR TITLE
include new ubi8 cuda-11.0.3 supporting python3.8 notebooks

### PR DESCRIPTION
**Pull request by harshad16**
include new ubi8 cuda-11.0.3 supporting python3.8 notebooks
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Comment by crobby** [comment]
Maybe add something in a readme to call attention to the memory requests/limits when enabling this overlay.  I suppose if someone has a fancy GPU in their cluster, they probably aren't all that tight on memory, but it does represent a bump over the usual minimal installation.

**Comment by nakfour** [comment]
@harshad16 can you please describe how to test this, also do we need to make changes to the Readme file to describe this new overlay?

**Comment by nakfour** [comment]
@harshad16 also does this need CI tests added?

**Comment by LaVLaS** [comment]
There are no existing CI tests for any of the `cuda` or notebook image builds.  For automated CI runs in prow, as far as i know, we can only test that the images build successfully and we can run non-gpu notebooks without error.  IMO, this would need to be a standalone CI run because doing image builds that include cuda would probably take 3-4hrs minimum for build and verification.

We should create a separate story for the creation a build and verify notebook test suite.

**Comment by LaVLaS** [comment]
Is this `cuda-11.0.3` compatible with a `10.1` build? If so can this replace the existing `cuda` overlay with the default `cuda_version=11.0.3`?

**Comment by harshad16** [comment]
> Is this `cuda-11.0.3` compatible with a `10.1` build? If so can this replace the existing `cuda` overlay with the default `cuda_version=11.0.3`?

the version of cuda picked is based on the version of the tensorflow we are providing, to better explain,
- we have python3.6 notebook with tensorflow 2.3.1 which is compatible with cuda10.1 i.e why we have cuda overlay with that version.
- This is with python3.8 notebook with tensorflow 2.4.1 which is compatible with cuda11.0.3 i.e why we have this overlay separate.

**Review by LaVLaS — CHANGES_REQUESTED** [review]
Can you also add an entry to the main jupyterhub readme under `notebook-image` [overlays](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub#notebook-images)?  It only needs a one line summary with a link to your `cuda-11.0.3` readme.

**Comment by harshad16** [comment]
Ready for review @crobby and @LaVLaS

**Comment by harshad16** [comment]
can someone help with me the e2e check issue, I m not able to figure it out.

**Comment by crobby** [comment]
@harshad16 Sorry...just saw the note about the test now.
First step, I'd try a rebase of this PR.

**Comment by harshad16** [comment]
> First step, I'd try a rebase of this PR.

@crobby , it is up-to-date with the current master head.is there something i m missing?

**Comment by crobby** [comment]
> > First step, I'd try a rebase of this PR.
> 
> @crobby , it is up-to-date with the current master head.is there something i m missing?

Ok.  Hopefully, it was just a flake of some sort.  I'll try the test again.

**Comment by crobby** [comment]
The screenshot from the failure seems to show the elyra interface and the selenium test isn't finding an element it's looking for:  https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/opendatahub-io_odh-manifests/368/pull-ci-opendatahub-io-odh-manifests-master-odh-manifests-e2e/1379437816001335296/artifacts/odh-manifests-e2e/e2e/artifacts/screenshots/exception.png

**Comment by crobby** [comment]
The same problem in the test here that happened in the nightly run (against master).  I think there is a problem that slipped-in to master somehow.
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/logs/periodic-ci-opendatahub-io-odh-manifests-master-odh-manifests-e2e-nightly/1379592494982893568

**Comment by LaVLaS** [comment]
/retest

Looks like an `ImagePullBackOff` in the notebook pod for `s2i-minimal-notebook:v0.0.7`.

**Comment by crobby** [comment]
> /retest
> 
> Looks like an `ImagePullBackOff` in the notebook pod for `s2i-minimal-notebook:v0.0.7`.

good find....interesting though

**Review by harshad16 — COMMENTED** [review]
/hold 

kustomize patch causes issue

**Comment by harshad16** [comment]
/unhold
all fixed, ready for review

**Review by LaVLaS — APPROVED** [review]

**Review by LaVLaS — CHANGES_REQUESTED** [review]

**Review by LaVLaS — APPROVED** [review]
Deployed and tested tensorflow & pytorch in an gpu enabled OCP cluster

**Pull request merged**
