### PR TITLE
Update elyra notebook image to v0.1.4

### PR DESCRIPTION
**Pull request by akchinSTC**
This PR updates the manifest to pull in the latest version of elyra (3.9.1)

New features can be found in the following links: (See all links for all features, last published version of elyra was 3.6.0 in ODH)
https://github.com/elyra-ai/elyra/releases/tag/v3.9.1
https://github.com/elyra-ai/elyra/releases/tag/v3.9.0
https://github.com/elyra-ai/elyra/releases/tag/v3.8.0
https://github.com/elyra-ai/elyra/releases/tag/v3.7.0

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Comment by ptitzler** [comment]
@VaishnaviHire can you please review? Thank you!

**Comment by VaishnaviHire** [comment]
@akchinSTC Just want to verify if https://github.com/elyra-ai/examples/tree/main/pipelines/introduction-to-generic-pipelines is still a valid example for this version of elyra

**Comment by akchinSTC** [comment]
@VaishnaviHire - yes that example should still work. Also we have made improvements the kfp components side of things so suggest trying this as well : https://github.com/elyra-ai/examples/tree/main/pipelines/kubeflow_pipelines_component_examples/run_notebook_component
Thanks for the help!

**Comment by LaVLaS** [comment]
/lgtm

The generic pipelines support worked for me.  

@akchinSTC For right now, we will only verify the Elyra generic pipeline workflow until ODH has a supported deployment of KFP

**Review by LaVLaS — APPROVED** [review]

**Comment by shalberd** [comment]
Will Elyra 3.10.0 and higher be included on ODH 1.3.0? I am asking because the Eylra maintainers added http basic auth to airflow pipeline custom components download from urls, which is very valuable for enterprise-internal use (think e,g, Artifactory and a repo that is secured by basic auth methods).

https://github.com/elyra-ai/elyra/blob/v3.10.0/elyra/pipeline/airflow/package_catalog_connector/airflow_package_catalog_connector.py#L77

https://github.com/elyra-ai/elyra/blob/v3.10.0/elyra/pipeline/airflow/provider_package_catalog_connector/airflow_provider_package_catalog_connector.py#L82

**Pull request merged**
