### PR TITLE
Add DSP Operator specific labels

### PR DESCRIPTION
**Pull request by DharmitD**
This reverts commit f3581ae6deabf5fdd7d4bf67d976211bee3435c9.
Related task: https://github.com/opendatahub-io/data-science-pipelines-operator/issues/140

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Comment by shalberd** [comment]
@DharmitD 

I got an error after applying this

```
time="2023-06-29T10:40:35Z" level=warning msg="Encountered error applying application data-science-pipelines-operator:  (kubeflow.error): Code 500 with message: Apply.Run : Deployment.apps \"data-science-pipelines-operator-controller-manager\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\"app.kubernetes.io/name\":\"data-science-pipelines-operator\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable"
time="2023-06-29T10:40:35Z" level=warning msg="Will retry in 41 seconds."
```

looks like selectors are immutable, making updates from previous recipes problematic:.

https://www.datree.io/resources/kubernetes-error-codes-field-is-immutable

The only way I got this to work was to delte the old service, role, clusterrole, rolebinding and most of all deployment.
Sorry, the step from the old labels to the new ones has never been tested in a rollover scenario with KfCtl / ODH Operator.

**Pull request merged**
