### PR TITLE
Sync odh-notebook-controller v1.7 manifests to odh-manifests

### PR DESCRIPTION
**Pull request by harshad16**
Sync odh-notebook-controller v1.7 manifests to odh-manifests

## Description
Fixes: https://github.com/opendatahub-io/kubeflow/issues/56
synced the odh-notebook-controller v1.7 manifests

## How Has This Been Tested?

- setup the openshift-cluster
- install opendatahub operator
- deploy the kfdef with this branch
- test the notebook.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by atheo89** [comment]
Deployed a KfDef using this Pull request
```
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/pull/875/head'
status:
  conditions:
    - lastUpdateTime: '2023-07-21T08:19:56Z'
      reason: Kubeflow Deployment completed
      status: 'True'
      type: Available
```
The deployment was completed successfully. The Operator can spawn notebooks from the Jupyter tile or the Data Science Projects without issues. The logs for both controllers don't appear to have any unusual errors.  

However, I saw on the [trivial_conversion_patch.yaml](https://github.com/opendatahub-io/odh-manifests/blob/master/odh-notebook-controller/kf-notebook-controller/crd/patches/trivial_conversion_patch.yaml#L7) that an option should be deleted for the 1.7 release.

Overall, /lgtm

**Comment by LaVLaS** [comment]
/lgtm
/approve

If the CI test fails due to the trustyAI operator test, I will merge this since the local test ran successfully

**Comment by harshad16** [comment]
Rebased and pushed to get the tested fixed
Screenshot from 2023-07-21 13-58-14

This PR is required as we would like to extend v1.7 notebook-controller in ODH v1.8
Please get this in v1.8 
cc: @LaVLaS

**Pull request merged**
