### PR TITLE
Update access arguments for the ds pipelines UI

### PR DESCRIPTION
**Pull request by rimolive**
## Description
We discovered an issue where users require cluster admin in order to be able to access the ML Pipelines UI. Only view (or similar) level permissions should be required on the namespace. This change modifies the parameters for the ds pipelines oauth proxy to match what we're using now in other pods in the ODH.

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by LaVLaS** [comment]
@rimolive It looks like this resolves an issue in the current version of DS Pipelines.  Do you want to keep holding this or can it be reviewed now?

**Comment by rimolive** [comment]
@LaVLaS It can be reviewed now, as I already tested in an environment.

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
