### PR TITLE
Add pod anti-affinity to odh-model-controller manifests

### PR DESCRIPTION
**Pull request by israel-hdez**
## Description
Since the manager pod has 3 replicas, the anti-affinity rules are added to prefer (not require) scheduling the replicas in different worker nodes, rather than having replicas on the same node.

## How Has This Been Tested?
By deploying using the following KfDef:

```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-core
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      parameters:
      - name: monitoring-namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: model-mesh
    name: model-mesh
  - kustomizeConfig:
      parameters:
      - name: deployment-namespace
        value: opendatahub
      repoRef:
        name: manifests
        path: modelmesh-monitoring
    name: modelmesh-monitoring
  repos:
  - name: manifests
    uri: https://github.com/israel-hdez/odh-manifests/tarball/add-model-controller-anti-affinity
  version: add-model-controller-anti-affinity
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@Jooho @israel-hdez do you know if there's any automation planned for such changes? I think with all the controllers we have in place that would really be helpful.

**Comment by israel-hdez** [comment]
> do you know if there's any automation planned for such changes?

@bartoszmajsak Which changes? I think I'm not following :-)

**Comment by bartoszmajsak** [comment]
> > do you know if there's any automation planned for such changes?
> 
> @bartoszmajsak Which changes? I think I'm not following :-)

@israel-hdez ok maybe I should have been a bit more concrete. For example you change RBAC in your controller kubebuilder directives. This results in updating kustomize manifests in the controller repo. Is the update here done manually? I was thinking this could be automated. Or maybe it already is. I'm just lazy and tend to forget things :)

**Comment by israel-hdez** [comment]
> I was thinking this could be automated. Or maybe it already is.

OK, now I understand!
Well, I don't know of any automation, nor any planned one. So, it is manual for now.

And I agree automation would be helpful!

**Comment by Jooho** [comment]
@bartoszmajsak Yes that is a good point. The main manifests that we are using for modelmesh related repositories are in the modelmesh-serving/opendatahuh/odh-manifests.  So I think this kind of copying PR can be automated at some time.
However, we have full of high-priority tasks on the plate so I don't know when we can add this automation properly.

**Review by Jooho — APPROVED** [review]
/lgtm

**Pull request merged**
