### PR TITLE
[JupyterHub] Fix auth for prometheus /metrics endpoint behind auth proxy

### LINKED ISSUE #314: [JH] update to new JH version breaks metrics scraping
After the recent jupyterhub update, the `/metrics` enpoint is protected behind the auth proxy by default. We need to manually change the configuration to make `/metrics` endpoint scrapable.

We made this change in the MOC operate-first environment (PR: https://github.com/operate-first/apps/pull/255)

### PR DESCRIPTION
**Pull request by wseaton**
fixes #314 

relies on: https://github.com/opendatahub-io/jupyterhub-odh/pull/77

### CODE REVIEW

**Comment by anishasthana** [comment]
cc @4n4nd @maulikjs

**Comment by wseaton** [comment]
@anishasthana looks like the tests flaked? (although I'm not sure what I'm looking at, I see mostly timeouts)

**Comment by anishasthana** [comment]
Well, one less test failed this time. I'm wondering if it's still just flaking.

**Comment by wseaton** [comment]
@anishasthana noticed my KfDef was failing to apply, and it looks like my sample secret wasn't properly b64 encoded, fixed that!

**Comment by crobby** [comment]
/test all
gcp cluster creation is flaking at the moment....gcp-ci admin seems to be on it.  If it fails again, try rerunning again later.

**Comment by crobby** [comment]
/test odh-manifests-e2e
jh timeout flake (hopefully)

**Comment by crobby** [comment]
/test odh-manifests-e2e
Cluster install failed

**Comment by wseaton** [comment]
There was a hidden `\n` at the end of my secret :upside_down_face:, fixed that and retested the PR by cherry picking it onto my custom manifests and it appears to be working.

We still need to couple a jupyterhub-odh update with this to actually take advantage of it.

**Comment by LaVLaS** [comment]
/retest

Is this still blocked until https://github.com/opendatahub-io/jupyterhub-odh/pull/77 merges?

**Comment by wseaton** [comment]
@LaVLaS yes, without https://github.com/opendatahub-io/jupyterhub-odh/pull/77 getting merged and a version bump this PR doesn't solve anything, a 403 will still happen since the Prometheus token will be unset

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
