### PR TITLE
Update dsp to v1.1.0

### PR DESCRIPTION
**Pull request by HumairAK**
## Description
Update dsp to v1.1.0

[Release notes](https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v1.1.0)

## How Has This Been Tested?
Deploy kfdef with DSPO pointed to this fork and[ create a simple dspa](https://github.com/opendatahub-io/data-science-pipelines-operator#deploy-dsp-instance)

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by LaVLaS** [comment]
OCP 4.12 failed with the same known issue that is blocking the installation of any OLM operators on the cluster.  
Since the OCP4.11 test ran without issue and the OCP 4.12 issue is outside of our control, I am merging this.  The OCP 4.12 failure should be resolved later this week

**Comment by HumairAK** [comment]
I have been trying since friday to get this merged, tests are failing at random points, sometimes they fail to set up the cluster, other times they fail for other components that are not related to the pr. Latest failure: 

```
 ✘ FAILURE after 1209.590s: operator-tests/odh-manifests/basictests/trustyai.sh:72: executing 'oc logs pod/trustyai-service-68686476c9-826r5' expecting any result and text 'Received partial input payload'; re-trying every 10s until completion or 1200.000s: the command timed out 
 
 ```

**Comment by LaVLaS** [comment]
Based on the success of the ODH 4.11 tests we should be good to merge this.  The OCP 4.12 failure looks like a separate openshift-ci infrastructure issue and I will try to debug in a few hours.

**Comment by HumairAK** [comment]
@LaVLaS can you merge it?

**Comment by LaVLaS** [comment]
Merging this since the OCP 4.12 failure appears to be related to GCP infra issues

**Pull request merged**
