### PR TITLE
Add "additional" notebook images overlay

### PR DESCRIPTION
**Pull request by LaVLaS**
Add Elyra notebook as part of the new additional notebooks

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

## Description
Adds new Elyra notebook as an `additonal` overlay for `notebook-images`

## How Has This Been Tested?
Successfully deployed and spawned this notebook using

## Merge criteria:
1. Deploy ODH with the `additional` overlay enabled for `notebook-images`
2. Login  to odh-dashboard and spawn an Elyra notebook
3. Confirm that the notebook spawned successfully and Elyra functionality works

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Worked well with ocp 4.11

/lgtm

**Comment by LaVLaS** [comment]
@atheo89 @VaishnaviHire Feel free to recommend a different layout for the `additional` overlay.  I wanted to provide some separation between `odh-core` notebooks and fully supported (but not core) notebooks in our org

**Comment by atheo89** [comment]
@LaVLaS I totally agree with you on the separation of the notebooks, the `additional` looks good to me. What do you think to rename the `base` folder as `core` or `odh-core`?

**Pull request merged**
