### PR TITLE
Syn odh-manifest(odh-nightlies) for modelmesh-serving and odh-model-c…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…ontroller

odh-nightlies branch of odh-manifest is used to provide `fast` build to testing team. Motive with this PR is to provide latest manifest from modelmesh-serving and odh-model-controller.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by Jooho** [comment]
To me, the manifests look good but we need a description and test steps.
Even though it is a simple pr, we need to know what this pr is for and how to test it. 

Please update descrption.

**Comment by vaibhavjainwiz** [comment]
@Jooho @VedantMahabaleshwarkar 

Testing instruction :
- Create a new cluster
- Install the operator
- Specify custom manifests from the PR branch
```
apiVersion: dscinitialization.opendatahub.io/v1alpha1
kind: DSCInitialization
metadata:
  name: example
spec: 
  manifestsUri: https://github.com/vaibhavjainwiz/odh-manifests/tarball/sync_manifest
```
- Try to deploy a model

**Comment by vaibhavjainwiz** [comment]
I had updated the description on the top itself.

**Review by VedantMahabaleshwarkar — APPROVED** [review]
deployed ODH Operator v2.1.0 with `manifestsUri: https://github.com/vaibhavjainwiz/odh-manifests/tarball/sync_manifest`. 
Verified that modelmesh-controller and odh-model-controller deployments had the correct `fast` tag images for ODH Nightly builds. 
```
Successfully pulled image "quay.io/opendatahub/modelmesh-controller:fast" in 2.661463236s (2.661473419s including waiting)
```
```
Successfully pulled image "quay.io/opendatahub/odh-model-controller:fast" in 1.725552819s (1.725568294s including waiting)
```  

/lgtm

**Pull request merged**
