### PR TITLE
Allow tests to use git branch/commit for ods-ci repo

### PR DESCRIPTION
**Pull request by LaVLaS**
Quick workaround for [ODH-576](https://issues.redhat.com/browse/ODH-576) to unblock JupyterHub CI failures with 'Invalid SemVer`

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

### CODE REVIEW

**Review by crobby — APPROVED** [review]
lgtm, but tests still died, looking at the fail

**Comment by LaVLaS** [comment]
/hold

Holding this until https://github.com/red-hat-data-services/ods-ci/pull/175 is merged which should resolve the CI issues.  I will keep this PR open to add the ability to specify the ods-ci branch when building the peak container

**Review by crobby — APPROVED** [review]
lgtm

**Pull request merged**
