### PR TITLE
Update to spark 1.1.0 and use OLM subscription for install

### PR DESCRIPTION
**Pull request by LaVLaS**
Spark fails to deploy on OCP 4.6 preview builds. This pulls in the latest version of spark that will resolve those issues. Switching to using the OLM subscription to install spark

### CODE REVIEW

**Comment by vpavlin** [comment]
@LaVLaS Any particular reason why you removed `spark` subdir? I think `radanalyticsio` by itself is not exaplanatory enough for users to easily understand that this is spark operator

**Comment by LaVLaS** [comment]
> @LaVLaS Any particular reason why you removed `spark` subdir? I think `radanalyticsio` by itself is not exaplanatory enough for users to easily understand that this is spark operator

I only removed it so it matche the dir format of the other apps that install via OLM subscriptions.

**Comment by crobby** [comment]
/test all

gcp quota issues.  According to the gurus, we should be good to go now.

**Comment by crobby** [comment]
/test all

(cluster problem appears to be fixed, but the last run acted like the ODH operator wasn't doing anything)

**Comment by crobby** [comment]
/test all
Again, it behaved like our operator wasn't doing anything.  Probably time for some debugging.

**Comment by crobby** [comment]
/test all
This is just beyond silly now

**Comment by crobby** [comment]
/test all
Known openshift-ci outage...they say to retry

**Comment by crobby** [comment]
@LaVLaS According to the log of the tests, the operator pod was running, but I'm not seeing any pods in the opendatahub project.  Might be useful to add a dump of the log from the opendatahub-operator pod.

**Comment by crobby** [comment]
@LaVLaS Looks like the operator install is maybe hanging again.  I have a PR to hopefully fix this:  https://github.com/opendatahub-io/odh-manifests/pull/205  Once that merges, maybe a rebase and try again.

**Comment by crobby** [comment]
/test all
Cluster spawn on gcp failed....again

**Comment by crobby** [comment]
Finally may have a "real" test error:  operator-tests/odh-manifests/basictests/radanalytics.sh:19

**Pull request merged**
