### PR TITLE
Update Notebook Controllers to v1.6.1

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Description
This PR includes all the changes required for notebook controllers to update to v1.6.1

## How Has This Been Tested?
1. Install Open Data Hub Operator
2. Create `odh-core` KfDef with manifests pointing to `https://github.com/VaishnaviHire/odh-manifests/tarball/update_to_KF-161`

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by shalberd** [comment]
Maybe the change for supporting openshift installations without internal docker registry can make it into v1.5.1.

https://github.com/opendatahub-io/kubeflow/pull/72

that will necessitate changes in the ODH Dashboard notebook assembly, though (annotation and others).

https://github.com/opendatahub-io/odh-dashboard/pull/800

I would have liked it to be in v1.5.0, but with March 25, seems like all is set for now.

**Comment by VaishnaviHire** [comment]
> Maybe the change for supporting openshift installations without internal docker registry can make it into v1.5.1.
> 
> [opendatahub-io/kubeflow#72](https://github.com/opendatahub-io/kubeflow/pull/72)
> 
> that will necessitate changes in the ODH Dashboard notebook assembly, though (annotation and others).
> 
> [opendatahub-io/odh-dashboard#800](https://github.com/opendatahub-io/odh-dashboard/pull/800)
> 
> I would have liked it to be in v1.5.0, but with March 25, seems like all is set for now.

Hi Sven, we can cut another Notebook controller release once your PR is merged. 

cc: @LaVLaS

**Comment by shalberd** [comment]
> Hi Sven, we can cut another Notebook controller release once your PR is merged.

Yes. If you can, also try the changes / images from both PRs on a system that does have the internal openshift registry. It'll fill out the image-field referencing the registry/imagestreamnamespace/image as usual in the case of internal registry.

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
Note: From the logs, the notebook controller pods seemed to be running. Rebased and triggered retest

**Comment by VaishnaviHire** [comment]
e2e tests failed to curl `notebook/api` endpoint. This endpoint is no longer exposed from outside the notebook pod. 
Updated and verified the tests to [remove](https://github.com/opendatahub-io/odh-manifests/pull/759/files#diff-71fe2223781a326ddcb51e48988502e3b89b680395a1ff6935f81f9a92ac400eL67) the test step that curls the endpoint

**Pull request merged**
