### PR TITLE
feat(prometheus): Upgrade operator to 0.47.0

### PR DESCRIPTION
**Pull request by tumido**
SSIA

### CODE REVIEW

**Comment by tumido** [comment]
merged upstream

/unhold

**Comment by tumido** [comment]
it may yet not arrived in the catalog, the tests may still fail...

**Comment by tumido** [comment]
/retest
Failure unrelated to the change

**Review by crobby — APPROVED** [review]

**Comment by tumido** [comment]
CI complaining about jupyterhub, I'll try rebasing and retesting

/retest

**Comment by tumido** [comment]
E2E is reporting unrelated failure again:
```
✔ SUCCESS after 0.214s: operator-tests/odh-manifests/basictests/trino.sh:27: executing 'oc get pods -l role=trino-worker --field-selector='status.phase=Running' -o jsonpath='{$.items[*].metadata.name}'' expecting any result and text 'trino-worker'; re-trying every 10s until completion or 1200.000s

Running operator-tests/odh-manifests/basictests/trino.sh:33: executing 'echo 3' expecting success and text '3'...


✔ SUCCESS after 0.015s: operator-tests/odh-manifests/basictests/trino.sh:33: executing 'echo 3' expecting success and text '3'

/root/peak/operator-tests/odh-manifests/resources/kafka/image No [INFO] by in regex selected tests were
Already on project "opendatahub" on server "https://api.ci-op-z45idpk9-45a7f.*********************************:6443".
One or more tests failed:

	/root/peak/operator-tests/odh-manifests/basictests/radanalytics.sh

/root/peak/run.sh took 1592 seconds
[INFO] Exiting with 1
+ '[' 1 -ne 0 ']'
+ echo 'The tests failed'
The tests failed
+ success=0
+ echo 'Saving the dump of the pods logs in the artifacts directory'
Saving the dump of the pods logs in the artifacts directory
+ oc get pods -o yaml -n opendatahub
+ oc get pods -o yaml -n openshift-operators
+ echo 'Saving the events in the artifacts directory'
Saving the events in the artifacts directory
+ oc get events '--sort-by={.lastTimestamp}'
+ echo 'Saving the logs from the opendatahub-operator pod in the artifacts directory'
Saving the logs from the opendatahub-operator pod in the artifacts directory
++ oc get pods -n openshift-operators -l name=opendatahub-operator -o 'jsonpath={$.items[*].metadata.name}'
+ oc logs -n openshift-operators opendatahub-operator-5c9f6f76b8-knjc8
+ '[' 0 -ne 1 ']'
+ exit 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-04-29T16:58:26Z"}
error: failed to execute wrapped command: exit status 1
```

What can I do with this, can you help me please? @LaVLaS @nakfour :slightly_smiling_face:

**Pull request merged**
