### PR TITLE
New component: ODH Notebook Controller

### PR DESCRIPTION
**Pull request by samuelvl**
This PR includes the following changes:

- Generate `KfDef` compatible manifests for the [Kubeflow Notebook Controller](https://github.com/opendatahub-io/kubeflow/tree/master/components/notebook-controller).
- Generate `KfDef` compatible manifests for the [Openshift Notebook Controller](https://github.com/opendatahub-io/kubeflow/tree/master/components/odh-notebook-controller).
- Add notebook-controller.sh tests.
- New Grafana dashboard with controller metrics to measure SLIs.
- Prometheus mock exporter with fake notebook controller metrics.
- Add minimal and generic notebooks example.

If you want to try out this PR you can use the following KfDef:

```yaml
---
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: notebook-controller
  namespace: opendatahub
spec:
  applications:
    - name: odh-common
      kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/cluster
      name: grafana-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: grafana/grafana
      name: grafana-instance
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/cluster
      name: prometheus-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: prometheus/operator
      name: prometheus-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: notebook-controller
      name: notebook-controller
  repos:
    - name: manifests
      uri: https://github.com/samuelvl/odh-manifests/tarball/notebook-controller
  version: master
```

Create a dummy secret to allow Prometheus to load service monitors:

```
oc create secret generic jupyterhub --from-literal="PROMETHEUS_API_TOKEN=foo" -n opendatahub
```

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
Worked well on 4.10 cluster.

Should we also update entries in the https://github.com/opendatahub-io/odh-manifests/tree/master/kfdef ?

**Comment by samuelvl** [comment]
> Should we also update entries in the https://github.com/opendatahub-io/odh-manifests/tree/master/kfdef ?

Added! Thanks for pointing it out, I had completely forgotten

**Comment by samuelvl** [comment]
/hold

Wait until https://github.com/opendatahub-io/kubeflow/pull/20 is merged

**Comment by LaVLaS** [comment]
> > Should we also update entries in the https://github.com/opendatahub-io/odh-manifests/tree/master/kfdef ?
> 
> Added! Thanks for pointing it out, I had completely forgotten

Instead of adding another component to the main kfdef, we should add a separate kfdef for dashboard, notebook-controllers and notebooks that we can build upon for updates

**Comment by samuelvl** [comment]
> Instead of adding another component to the main kfdef, we should add a separate kfdef for dashboard, notebook-controllers and notebooks that we can build upon for updates

Do you mean creating a different kfdef for every component? Would this be a valid example?

```yaml
$ cat kfdef/kfctl_odh_notebook_controller.yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: odh-notebook-controller
  namespace: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-notebook-controller
    name: odh-notebook-controller
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/master
  version: master
```

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
