### PR TITLE
Upgrade to KServe v0.11

### PR DESCRIPTION
**Pull request by israel-hdez**
Moving to KServe v0.11

Upstream release notes: https://github.com/kserve/kserve/releases/tag/v0.11.0

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by LaVLaS** [comment]
@israel-hdez Can you add a link to any release notes / change log for this update?

**Comment by israel-hdez** [comment]
@LaVLaS We can use upstream release notes: https://github.com/kserve/kserve/releases/tag/v0.11.0

**Review by heyselbi — APPROVED** [review]

**Pull request merged**
