### PR TITLE
Add the oauth proxy in front of kfp ui

### PR DESCRIPTION
**Pull request by accorvin**

### CODE REVIEW

**Review by gmfrasca — APPROVED** [review]

**Comment by accorvin** [comment]
Here is a kfdef that can be used to test this (may/will need to change the namespace):
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: kfp
spec:
  applications:
    - kustomizeConfig:
        overlays:
          - ml-pipeline-ui
          - metadata-store-mysql
        repoRef:
          name: manifests
          path: ml-pipelines
      name: ml-pipeliens
  repos:
    - name: manifests
      uri: 'https://github.com/accorvin/idh-manifests/tarball/add-kfp-auth'
```

**Comment by accorvin** [comment]
This can be tested at https://ml-pipeline-ui-kfp.apps.acorvin.zipv.s1.devshift.org/

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
