### PR TITLE
Update Jupyter Notebook buildConfigs with Thoth urls and envs

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by vpavlin** [comment]
Fixes: #73

**Comment by LaVLaS** [comment]
This is failing for me because `nbviewer-buildconfig.yaml` was deleted but it is still referenced in `build/kustomization.yaml`

**Comment by vpavlin** [comment]
Ups...last minute changes without verification..fixed now..

**Comment by nakfour** [comment]
This worked for me.

**Pull request merged**
