### PR TITLE
update modelmesh manifests to use 0.11.0

### PR DESCRIPTION
**Pull request by Jooho**
## Description

modelmesh/kserve synced with v0.11 so this odh-manifests needs to be updated.

## How Has This Been Tested?

- Install odh operator v2.x
- add manifestsUri into DSCInitialization
~~~
apiVersion: dscinitialization.opendatahub.io/v1alpha1
kind: DSCInitialization
metadata:
  name: default
spec:
  applicationsNamespace: opendatahub
  manifestsUri: 'https://github.com/Jooho/odh-manifests/tarball/0.11'
  monitoring:
    enabled: false
    namespace: opendatahub
~~~
- Create DSC
~~~
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
kind: DataScienceCluster
metadata:
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: opendatahub-operator
  name: default
spec:
  components:
    codeflare:
      enabled: false
    dashboard:
      enabled: false
    datasciencepipelines:
      enabled: false
    kserve:
      enabled: false
    modelmeshserving:
      enabled: true
    ray:
      enabled: false
    workbenches:
      enabled: false
~~~

- Create a ServingRuntime and deploy isvc
~~~
git clone git@github.com:opendatahub-io/modelmesh-serving.git
cd modelmesh-serving

STABLE_MANIFESTS=true CONTROLLERNAMESPACE=opendatahub NAMESPACE=modelmesh-serving  make deploy-fvt-for-odh

oc apply -n modelmesh-serving -f https://raw.githubusercontent.com/opendatahub-io/modelmesh-serving/main/opendatahub/quickstart/common_manifests/openvino-serving-runtime.yaml

oc apply -n modelmesh-serving -f https://raw.githubusercontent.com/opendatahub-io/modelmesh-serving/main/opendatahub/quickstart/common_manifests/openvino-inference-service.yaml
~~~

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
/retest

@Jooho Are these test failures expected?

**Comment by Jooho** [comment]
@VaishnaviHire looks it failed with trustyAI part.

**Comment by VaishnaviHire** [comment]
Merging this PR, as the modelmesh tests passed.

cc: @Jooho @heyselbi

**Pull request merged**
