### PR TITLE
Dashboard Release v2.9.0

### PR DESCRIPTION
**Pull request by andrewballantyne**
Release notes: https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.9.0

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]

**Comment by andrewballantyne** [comment]
/retest

It passed before the approval haha... gotta be a flake. Possible something outside of our code caused this to fail, but will retest to see if it passes.

**Comment by LaVLaS** [comment]
@andrewballantyne @lucferbux 

I am seeing the error below when deploying the dashboard locally.  The last two CI runs are failing due to `Application is not available ([Screenshots](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/opendatahub-io_odh-manifests/770/pull-ci-opendatahub-io-odh-manifests-master-odh-manifests-e2e/1645783138443464704/artifacts/odh-manifests-e2e/e2e/artifacts/ods-ci-2023-04-11-14-28-0opFbRWKJZ/)) when accessing the dashboard route

```
> ods-dashboard-backend@1.0.0 start
> NODE_ENV=production node ./dist/server.js --log=1 --registry=localhost:50051

npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/.npm/_cacache/tmp/a99da38d
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000690000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

**Comment by LaVLaS** [comment]
@andrewballantyne @lucferbux Are you going to do a odh-dashboard release of v2.9.1 or wait for a v2.10 release?

**Comment by andrewballantyne** [comment]
Ah right -- I forgot about this being related to the build issue -- release is tomorrow, 2.10 it is. Sorry about that 😅

**Comment by andrewballantyne** [comment]
I'm going to close this. We'll come back through fresh with 2.10 of the ODH Dashboard at the end of tomorrow.

**Pull request closed without merging**
