### PR TITLE
Add syntax highlighting to markdown

### PR DESCRIPTION
**Pull request by strangiato**
## Description
Set code language for syntax highlighting to all markdown files for code examples blocks.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by strangiato** [comment]
Looks like tests are passing after rebase.

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
