### PR TITLE
Update seldon operator version to v1.12.0

### PR DESCRIPTION
**Pull request by LaVLaS**
Update the seldon certified operator version to v1.12.0

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

### CODE REVIEW

**Comment by HumairAK** [comment]
nvm -- this loooks like it's in direct conflict with: https://github.com/opendatahub-io/odh-manifests/pull/522/

**Comment by LaVLaS** [comment]
Closing this since the `startingCSV` was removed in #522

**Pull request closed without merging**
