### PR TITLE
Bump up the memory limit for traefik-proxy

### PR DESCRIPTION
**Pull request by maulikjs**
We have had the container restart a couple of times due to it being OOMKilled in our internal deployment, this should take care of that problem for good.

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
/lgtm

@maulikjs can you take this downstream as well?

**Comment by maulikjs** [comment]
ack

**Comment by crobby** [comment]
Is there a Jira for this change?

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
