### PR TITLE
Disable virtual host functionality of kserve

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by israel-hdez** [comment]
Changes to `kserve-built` can be overriden by local patches.

We have one here for this ConfigMap: https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/base/inferenceservice-config-patch.yaml.

You should apply the change in that patch rather than in `kserve-built`. Unfortunately, that patch is outdated. You will need to wait for https://github.com/opendatahub-io/odh-manifests/pull/908 to go in and apply your changes on top of that.

**Comment by vaibhavjainwiz** [comment]
> Changes to `kserve-built` can be overriden by local patches.
> 
> We have one here for this ConfigMap: https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/base/inferenceservice-config-patch.yaml.
> 
> You should apply the change in that patch rather than in `kserve-built`. Unfortunately, that patch is outdated. You will need to wait for #908 to go in and apply your changes on top of that.

@israel-hdez I had done the requested changes, could you please review it again.

**Comment by israel-hdez** [comment]
@vaibhavjainwiz Can you, please, squash to a single commit?

**Comment by vaibhavjainwiz** [comment]
> @vaibhavjainwiz Can you, please, squash to a single commit?

done.. I had squash to a single commit.

**Review by heyselbi — APPROVED** [review]

**Comment by LaVLaS** [comment]
There are 2 possible fixes for the CI test fallures that are not related to changes in this PR.  If those known failures exist in this PR, I will manually merge this to get it unblocked

**Comment by heyselbi** [comment]
@LaVLaS yep, the e2e [ci tests](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_odh-manifests/916/pull-ci-opendatahub-io-odh-manifests-master-odh-manifests-e2e/1692170091749183488) are failing because of codeflare and ray related issues (ie. not related to this PR).

**Comment by LaVLaS** [comment]
I'm waiting on the outcome of #910 to see if it fixes the CI failures.  If Yes, then we should be able to rebase and the CI/CD will be back to normal after a rebase.

If any of those tests in #910 fail, I'll merge this PR manually

**Comment by LaVLaS** [comment]
Merging this since it was blocked by the Distributed Workloads test failures that were resolved in #910.  The modelmesh test is failing and will be fixed in #918 based on an offline conversation by @VedantMahabaleshwarkar

**Pull request merged**
