### PR TITLE
Add Makefile for releases

### PR DESCRIPTION
**Pull request by vpavlin**
To test this, make sure you are **not in opendatahub-io/odh-manifests** otherwise the `make` run will push new branch and tag to the repo:)

To try this out, run

```
make VERSION=1.2.3
```

It should result in creation of a branch `v1.2-branch` and a tag `v1.2.3` and it also updates the KFDef in the branch and tag to point to the tag

You can see it in my fork:

https://github.com/vpavlin/odh-manifests/releases/tag/v1.2.3
https://github.com/vpavlin/odh-manifests/tree/v1.2-branch

Other use cases that I tried to cover are 

* We do not want to release from the top of the master, but from a specific commit

```
make VERSION=1.3.5 UPDATE_TO_COMMIT=<commit-id-below-top-of-master>
```

* Creating a bugfix release with changes that were cherry-picked to a branch (e.g. v1.5-branch)

```
make tag VERSION=1.5.7
```

### CODE REVIEW

**Comment by LaVLaS** [comment]
Can we get your https://github.com/opendatahub-io/odh-manifests/pull/101#issue-421863595 added to a build doc?

**Comment by vpavlin** [comment]
Test

**Comment by crobby** [comment]
Should we have a default that echoes the usage for our Makefile since it's sort of a nontraditional Makefile (in that it doesn't build the software, instead, it manipulates tags in git)?

**Comment by vpavlin** [comment]
@crobby 

> Should we have a default that echoes the usage for our Makefile

I like it...added a help that is printed by default or in case `VERSION` is not defined

**Pull request merged**
