### PR TITLE
Add Pytorch to the mix kfdef

### PR DESCRIPTION
**Pull request by vpavlin**
Fixes: #147

### CODE REVIEW

**Comment by nakfour** [comment]
@vpavlin Can we rename the file to something meaningful. maybe kfctl_openshift_pytorch.yaml. We have so many different examples. Or maybe kfctl_openshift_distributed_training.yaml

**Comment by crobby** [comment]
> @vpavlin Can we rename the file to something meaningful. maybe kfctl_openshift_pytorch.yaml. We have so many different examples. Or maybe kfctl_openshift_distributed_training.yaml

Also, we should add the mixes to what we are testing.  Probably another PR for that though since it will require some reworking of the test wrapper.

**Comment by nakfour** [comment]
This worked for me.
/lgtm

**Pull request merged**
