### PR TITLE
Apply notebook digest as environment variables on imagestreams

### PR DESCRIPTION
**Pull request by atheo89**
Apply notebook digest as environment variables on imagestreams.

Fix for: https://github.com/opendatahub-io/odh-manifests/issues/819
## How Has This Been Tested?

- Deploy ODH with enabled the notebook-images
- Login to odh-dashboard and navigate into notebooks server spawner
- Ensure that the notebooks selection is in place
- Try to spawn a notebook 

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks :100:

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
