### PR TITLE
Integrate TrustyAI notebook into ODH

### PR DESCRIPTION
**Pull request by atheo89**
This PR Integrates the TrustyAI notebook into ODH

## Description
New files that have been added:

- `notebook-images/base/jupyter-trustyai-notebook-imagestream.yaml`
- `tests/resources/notebook-controller/notebooks/jupyter-trustyai-ubi9-python-3-9.yaml`

## Merge criteria:
Should be merged first this PR -> https://github.com/opendatahub-io/notebooks/pull/51
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by LaVLaS** [comment]
This needs to merge with #740 to ensure that the notebook works with the ODH Core deployment

**Comment by LaVLaS** [comment]
@RobGeada Can you verify that this notebook works as intended?

**Comment by VaishnaviHire** [comment]
@RobGeada any updates on this?

Should this be moved to 1.6 release ?

**Pull request merged**
