### PR TITLE
Adding basic test for seldon

### PR DESCRIPTION
**Pull request by nakfour**
This completes #99

### CODE REVIEW

**Comment by crobby** [comment]
Another ci-system flake.
/test all

**Comment by crobby** [comment]
flake
/test all

**Comment by crobby** [comment]
I was expecting another flake, but this one appears to be real.  To save you some log trolling:

✘ FAILURE after 0.405s: operator-tests/odh-manifests/basictests/seldon.sh:13: executing 'oc create -f /peak/operator-tests/odh-manifests/basictests/../resources/seldon-model.json' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server (InternalError): error when creating "/peak/operator-tests/odh-manifests/basictests/../resources/seldon-model.json": Internal error occurred: failed calling webhook "v1alpha2.mseldondeployment.kb.io": Post https://seldon-webhook-service.opendatahub.svc:443/mutate-machinelearning-seldon-io-v1alpha2-seldondeployment?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Seldon")

**Comment by nakfour** [comment]
@crobby if you clear the webhooks and install again., here is the exact error I see
```
controller-runtime.controller	Reconciler error	{"controller": "seldon-controller-manager", "request": "test-seldon/modelfull", "error": "Deployment.apps \"modelfull-modelfull-0-modelfull\" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: \"podinfo\", spec.template.spec.containers[0].volumeMounts[1].mountPath: Invalid value: \"/etc/podinfo\": must be unique]"}
```
in the seldon controller pod

**Comment by crobby** [comment]
flake
/test all

**Pull request merged**
