### PR TITLE
Bump TrustyAI to 1.9

### PR DESCRIPTION
**Pull request by RobGeada**
Updates the TrustyAI image to 1.9 from 1.8, which should fix the TrustyAI metrics not appearing in the model-monitoring stack.

## How Has This Been Tested?
Via TrustyAI's Openshift-CI

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by ruivieira** [comment]
For reference, monitoring PR in question (included in 1.9.0)

- https://github.com/trustyai-explainability/trustyai-service-operator/pull/81

**Review by tteofili — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
