### PR TITLE
set imagestream name same as the tag version

### PR DESCRIPTION
**Pull request by harshad16**
Related-To: https://github.com/opendatahub-io/odh-manifests/pull/304

set imagestream name same as the tag version
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

### CODE REVIEW

**Review by crobby — APPROVED** [review]

**Review by crobby — CHANGES_REQUESTED** [review]
The tests need to be updated to select the new image names in the UI

**Comment by vpavlin** [comment]
@harshad16 ah...i missed @crobby's comment - yes the list of images to test is here: https://github.com/opendatahub-io/odh-manifests/blob/master/tests/basictests/jupyterhub.sh#L14

**Review by crobby — APPROVED** [review]

**Pull request merged**
