### PR TITLE
Add images as variable in params.yaml for codeflare/ray

### PR DESCRIPTION
**Pull request by zdtsw**
## Description
- add image variable into codeflare (not in use)
- add image variable into ray and convert `images` to `vars`
- ref https://github.com/opendatahub-io/opendatahub-operator/issues/384
- ref https://github.com/opendatahub-io/opendatahub-operator/pull/389

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
@anishasthana you wanna take a look at this one?

**Comment by anishasthana** [comment]
Sure!

**Comment by zdtsw** [comment]
will have this one closed.
the purpose is to add variables into params.env file for new v2 operator to use.
the rest are converting syntax for kustomize v5.

**Comment by anishasthana** [comment]
All manifests go into the Distributed Workalods repo first -- I've opened a PR there.

**Pull request closed without merging**
