### PR TITLE
DSPO changes v0.2.0

### PR DESCRIPTION
**Pull request by HumairAK**
## Description
Bring v0.2.0 changes into odh-manifests.

Live builder image (if needed): quay.io/hukhan/rhods-operator-live-catalog:1.27.0-347
(ignore dashboard failures, unrelated)

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by gmfrasca — APPROVED** [review]

**Review by DharmitD — APPROVED** [review]
/Approve

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
