### PR TITLE
Update Elyra image to v0.1.2

### PR DESCRIPTION
**Pull request by akchinSTC**
High level summary of updates (let me know if more details are needed)

- Updated JupyterLab to 3.1
- KFP SDK support updated to 1.18.10 and KFP Tekton to 1.2.0
- Support for runtime specific pipelines while continuing to support generic components (classic notebookOp)
    - Support for KFP component definitions
    - Support for Airflow operators
- Support for runtime specific component catalogs
    - Includes support for catalog connectors
- Enhanced Elyra’s command line interface
- Enhanced pipeline editor GUI 
- Add pipeline validation service

Full release changeling available here : https://elyra.readthedocs.io/en/latest/getting_started/changelog.html#release-3-6-0-02-08-2022

### CODE REVIEW

**Comment by LaVLaS** [comment]
@akchinSTC Can you provide a quick summary of the updates included in this Elyra update for the ODH release notes?

**Comment by akchinSTC** [comment]
@LaVLaS absolutely, give me a bit to curate the change log since this is quite a big leap going from elyra 2.2.4 to 3.6.0.

**Comment by LaVLaS** [comment]
Thanks. Can you provide a link to a sample notebook that we can use to verify that Elyra is working.  Going forward we want to integrate this into our CI/CD runs to confirm that Elyra is working with each update

**Comment by LaVLaS** [comment]
> > Thanks. Can you provide a link to a sample notebook that we can use to verify that Elyra is working. Going forward we want to integrate this into our CI/CD runs to confirm that Elyra is working with each update
> 
> @LaVLaS - Just verifying that you want a sample **notebook** and not a sample **pipeline**

Both would be great.  I just want to make sure that we have something on hand to verify basic functionality of the Elyra notebook works. 

I assume that https://github.com/elyra-ai/examples/tree/master/pipelines/introduction-to-generic-pipelines is valid for this Elyra notebook version?  If so, are there any plans to add tags/releases for each elyra version?

**Comment by akchinSTC** [comment]
> > > Thanks. Can you provide a link to a sample notebook that we can use to verify that Elyra is working. Going forward we want to integrate this into our CI/CD runs to confirm that Elyra is working with each update
> > 
> > 
> > @LaVLaS - Just verifying that you want a sample **notebook** and not a sample **pipeline**
> 
> Both would be great. I just want to make sure that we have something on hand to verify basic functionality of the Elyra notebook works.
> 
> I assume that https://github.com/elyra-ai/examples/tree/master/pipelines/introduction-to-generic-pipelines is valid for this Elyra notebook version? If so, are there any plans to add tags/releases for each elyra version?

Yes that should work as both a pipeline and notebook sample/test pipeline. We unfortunately dont have any tagged releases for the examples. This topic came up briefly at one of our recent meetings, I will ask about the possibility of adding this to our release process.

**Comment by VaishnaviHire** [comment]
/lgtm

Updated Elyra image worked well on 4.9 OpenShift cluster. I was able to create the sample pipeline and add jupyter notebooks.
Screen Shot 2022-04-07 at 5 41 26 PM

**Comment by romeokienzler** [comment]
@LaVLaS in which ODH release will this be included? is there a way to test this specific manifest (e.g. pulling a master unstable version of the ODH operator into openshift)?

**Comment by romeokienzler** [comment]
just learned from @guimou that I need to simply modify the KfDef 
image

**Pull request merged**
