### PR TITLE
Pachyderm integration 

### PR DESCRIPTION
**Pull request by Jason4849**
Signed-off-by: Jooho Lee <ljhiyh@gmail.com>

This PR is about [ODH-554](https://issues.redhat.com/browse/ODH-554)

### CODE REVIEW

**Comment by anishasthana** [comment]
cc @nakfour

**Review by anishasthana — CHANGES_REQUESTED** [review]
@Jason4849  we need to add basic tests for pachyderm

**Comment by Jooho** [comment]
@anishasthana I added test part. Please review it

**Comment by anishasthana** [comment]
We'll still need to wait on https://github.com/opendatahub-io/opendatahub-community/pull/5 getting merged/approved. @crobby

**Comment by LaVLaS** [comment]
/hold

Holding this until https://github.com/opendatahub-io/opendatahub-community/pull/5 is merged

**Comment by Jooho** [comment]
I will create a new ticket with 1 commit.

**Pull request closed without merging**
