### PR TITLE
Remove ai-library as of the default CI basictests

### PR DESCRIPTION
**Pull request by LaVLaS**
This PR removes AI-Library CI tests for the PR runs and relocates the files into the `ai-library` component directory for future use.

### CODE REVIEW

**Comment by LaVLaS** [comment]
/retest

gcp issues

**Review by anishasthana — APPROVED** [review]
/lgtm

**Comment by crobby** [comment]
/test all
airflow failed

**Comment by crobby** [comment]
/test all
Airflow again??

**Comment by crobby** [comment]
/test all
total openshift-ci meltdown

**Comment by LaVLaS** [comment]
Rebased to pull in the trino component for CI runs

**Comment by crobby** [comment]
/test all
prometheus this time

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
