### PR TITLE
Add PR template for odh-manifests repo.

### PR DESCRIPTION
**Pull request by rimolive**
Template PR text below:

---
Title: \<Add a title here\>
---

**Changes proposed in this pull request**
\<Describe the changes added in this pull request\>

**Test instructions (required)**
\<Describe the steps to test the changes in this pull request\>

**Closing issues**
\<If this pull request closes an issue, list them here\>

**Test results**
\<Provide a report of the local test results\>

### CODE REVIEW

**Comment by rimolive** [comment]
Just FYI, I added the template text in this PR for formatting review.

**Comment by nakfour** [comment]
@rimolive can we add a block on running the CI tests and if they passed? Something like CI Test Run provide CI test run results

**Comment by rimolive** [comment]
@nakfour I think the openshift-ci bot is responsible for that and I can't get access to the CI tests before the bot.

**Comment by nakfour** [comment]
@rimolive developers should run our unittests locally before submitting the PR, thats what the question is about. It is not about the OCP CI test result.

**Comment by crobby** [comment]
Probably needs a rebase to pick-up the JH HA changes that impacted tests.

**Review by nakfour — APPROVED** [review]

**Pull request merged**
