### PR TITLE
DashboardConfig CRD Changes for 2.4.0

### PR DESCRIPTION
**Pull request by andrewballantyne**
Manually sync the CRD changes from ODH Dashboard v2.4.0.

### CODE REVIEW

**Review by DaoDaoNoCode — APPROVED** [review]
lgtm

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]

**Comment by LaVLaS** [comment]
@andrewballantyne @DaoDaoNoCode The next release is for ODH v1.4.1 to update dashboard to v2.3.1 and pull in the `*.dashboard.opendatahub.io` CRDs into the ODH "Owned" CRDs.  Is thi scompatible with that release?

**Comment by DaoDaoNoCode** [comment]
I don't think we have DSG for dashboard 2.3.1 so the feature flag could probably not work anywhere because we don't have the feature at all, but it doesn't hurt to bring the CRD in IMO. Or you can also hold this until the release with dashboard 2.4.0

**Pull request merged**
