### PR TITLE
Add env vars to JH so that we don't lose auth_state on restart

### PR DESCRIPTION
**Pull request by vpavlin**
NOTE: this still needs a new image release on jupyterhub-odh

Use this as odd-manifests repo in KFDEF: ~https://github.com/opendatahub-io/odh-manifests/tarball/feature/enable-auto-login~

 https://github.com/vpavlin/odh-manifests/tarball/feature/enable-auto-login

https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift.yaml#L122

### CODE REVIEW

**Comment by accorvin** [comment]
This change looks good to me. I'll +1 once you clean up the image reference (I assume that's blocked on merging the other PR)

**Review by accorvin — APPROVED** [review]

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
The JH test needs to be updated to account for the change.

**Comment by LaVLaS** [comment]
The JupyterHub CI test needs to be updated

I think you should be able to delete this line for it to pass https://github.com/opendatahub-io/odh-manifests/blob/master/tests/basictests/jupyterhub/jhtest.py#L182

**Pull request merged**
