### PR TITLE
Added subscription permission for dashboard memory/cpu fix.

### PR DESCRIPTION
**Pull request by cfchase**
for https://github.com/opendatahub-io/odh-dashboard/pull/178

### CODE REVIEW

**Comment by LaVLaS** [comment]
@cfchase Are you going to include the dashboard version update with this fix?

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by crobby** [comment]
Is this change still WIP, or can that be removed

**Review by crobby — APPROVED** [review]

**Review by crobby — APPROVED** [review]
/lgtm

**Review by LaVLaS — APPROVED** [review]
/lgtm

This does not resolve any issues in the current odh-manifests deployment of the v1.0 dashboard and is a planned update for the upcoming dashboard v2.0 release

**Pull request merged**
