### PR TITLE
Remove overriden field in KServe ConfigMap

### PR DESCRIPTION
**Pull request by israel-hdez**
The defaults of the `credentials` attribute in KServe's ConfigMap are good. Removing the override in local patch.

## How Has This Been Tested?
Using [Caikit demo](https://github.com/opendatahub-io/caikit-tgis-serving/tree/main/demo/kserve) to install KServe stack and deploy a model.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by Jooho — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
Merging this since there are two recent instances of the `odh-manifests-e2e` and `411-odh-manifests-e2e` tests running successfully.  The only failure yesterday appeared to be due to infra issues in openshift-ci

**Pull request merged**
