### PR TITLE
Update Elyra notebook image to v0.1.5

### PR DESCRIPTION
**Pull request by ptitzler**
This PR updates the manifest to pull in the latest version of Elyra (3.10.1).

New features can be found in the following links: 
- https://github.com/elyra-ai/elyra/releases/tag/v3.10.1
- https://github.com/elyra-ai/elyra/releases/tag/v3.10.0

This new version includes fixes/features that were requested by @guimou and @shalberd

### CODE REVIEW

**Comment by akchinSTC** [comment]
Do not merge yet. Bug with latest image.
See https://github.com/opendatahub-io/s2i-lab-elyra/issues/45

**Comment by akchinSTC** [comment]
Issue has been resolved, image has been rebuilt and correct version is installed 
image

**Comment by ptitzler** [comment]
The JupyterHub test appears to fail due to an issue that is not caused by the Elyra container image:
```
==============================================================================
Test-Odh-Jupyterlab-Notebook                                                  
==============================================================================
Can Launch Jupyterhub                                                 | FAIL |
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 104.0.5112.79 with binary path /usr/bin/google-chrome
```

A similar issue was also reported in another unrelated PR. How can we move forward?

**Comment by shalberd** [comment]
The only apparent discrepancy I am seeing is that s2i-minimal-notebook was upgraded to version tag 0.4.0 23 days ago.

https://github.com/thoth-station/s2i-minimal-notebook/pull/566

You are referencing 0.3.0 20 days ago in s2i-lab-elyra.

**Comment by akchinSTC** [comment]
@harshad16 - Hi again, do you know if we need to update to the latest s2i-minimal-notebook as our base image or is that unrelated to the test failures for this PR?

**Comment by harshad16** [comment]
@akchinSTC 
Base image update shouldn't be causing this issue.
as the old version should work as well.

seems like the test engine cant spin up jupyterhub , to launch the image and test 
feel like more of test engine failure.
@anishasthana  and @LaVLaS  any suggestion here ?

**Comment by shalberd** [comment]
@strangiato @bdattoma odh-manifests tests dockerfile was modified to work with Chrome 104.x

https://github.com/opendatahub-io/odh-manifests/blob/master/tests/Dockerfile

On 5 July, header checks for Chrome 102 were added in the ods-ci test suite. Could that be it?

https://github.com/red-hat-data-services/ods-ci/pull/445/commits/1b4368a56d14b5b941488688ad28b7459910a79d

**Comment by LaVLaS** [comment]
@ptitzler Can you rebase this PR to pull in the latest updates to the CI test framework?

**Comment by ptitzler** [comment]
Looks like tests are successful now. Thank you!

**Comment by LaVLaS** [comment]
/lgtm

@ptitzler I created #650 to start the process of adding Elyra CI tests to our system.  For future notebook updates you'll need to add tests to verify that the Elyra notebook loads successfully, generic pipelines work and it can integrate with our ml-pipelines deployment

**Comment by bdattoma** [comment]
> @strangiato @bdattoma odh-manifests tests dockerfile was modified to work with Chrome 104.x
> 
> https://github.com/opendatahub-io/odh-manifests/blob/master/tests/Dockerfile
> 
> On 5 July, header checks for Chrome 102 were added in the ods-ci test suite. Could that be it?
> 
> [red-hat-data-services/ods-ci@1b4368a](https://github.com/red-hat-data-services/ods-ci/commit/1b4368a56d14b5b941488688ad28b7459910a79d)

sorry I was out of office. I think the header in [red-hat-data-services/ods-ci@1b4368a](https://github.com/red-hat-data-services/ods-ci/commit/1b4368a56d14b5b941488688ad28b7459910a79d) shouldn't affect your run. The error you got about supported version of chrome I think was due to a mismatch between the installed version of chrome and the chromedriver in your /usr/bin directory. 
However, that header should be changed, thanks for spotting it. We'll fix it :)

**Pull request merged**
