### PR TITLE
Sync manifest changes from data-science-pipelines PRs

### PR DESCRIPTION
**Pull request by gmfrasca**
## Description
- Moves configurations to their own overlay (allows for custom deployments if `default-configs` overlay not included, allowing user to specify their own database/s3 object store providers, etc without ODH operator overwritting them)
- Updates Persistence Agent RBAC to ClusterRole/ClusterRoleBinding (fixes UI update issues and allows for flexible deployment of DSP app to any namespace)
- Updates ODH Application Tiles with updated repo links, documentation, metadata, etc.
- Updates DSP KfDef

## How Has This Been Tested?
To test, simply apply the kfdef to a cluster with a running ODH Operator: /kfdefs/kfctl_openshift_ds-pipelines.yaml
Verify by accessing the ds-pipeline-ui route, running the example pipeline, etc.
You can also access the route via `Launch Application` link in ODH Dashboard after Enabling the Application from the Explore tab.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by LaVLaS** [comment]
/approve

@gmfrasca The dashboard tile won't be supported with the ODH Core deployment until the ODH Core 1.4.1 release

**Pull request merged**
