### PR TITLE
add dynamic namespace to delegate-url oauth arg for odh-dashbaord

### PR DESCRIPTION
**Pull request by strangiato**
## Description
Splitting https://github.com/opendatahub-io/odh-manifests/pull/758 into two separate PRs

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by LaVLaS** [comment]
@strangiato Since odh-dashboard manifest updates will need to originate from github.com/opendatahub-io/odh-manifests, we should just drop the odh-dashboard update from #758 instead of opening this separate PR

**Comment by strangiato** [comment]
@LaVLaS Do you mean the update should originate from github.com/opendatahub-io/odh-dashboard instead of odh-manifests?

**Comment by LaVLaS** [comment]
> @LaVLaS Do you mean the update should originate from github.com/opendatahub-io/odh-dashboard instead of odh-manifests?

That is correct for odh-dashboard.  The data-science-pipelines change is only being considered for review because The source of truth for the manifests exists in this repo.

**Comment by LaVLaS** [comment]
Closing this since it needs to be included in an odh-dashboard releases once https://github.com/opendatahub-io/odh-dashboard/pull/1046 is merged

**Pull request closed without merging**
