### PR TITLE
Removing Data Science Pipelines' manifests

### PR DESCRIPTION
**Pull request by DharmitD**
## Description

Removing Data Science Pipelines' manifests from odh-manifests repository, the manifests will be managed by [the new Data Science Pipelines Operator](https://github.com/opendatahub-io/data-science-pipelines-operator).
Keeping the Data Science Pipelines' standalone (operator-less) manifests in the Data Science Pipelines' ([upstream](https://github.com/opendatahub-io/data-science-pipelines-operator) & [downstream](https://github.com/red-hat-data-services/data-science-pipelines-operator)) repositories.

Closes [RHODS-6927](https://issues.redhat.com/browse/RHODS-6927)
## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by HumairAK** [comment]
This lgtm. 

However this issue is blocked until https://github.com/opendatahub-io/odh-manifests/pull/729 is merged. Once that's done this will need to be rebaesd.

**Comment by LaVLaS** [comment]
@DharmitD Although we are replacing the existing `data-science-pipelines` deployment with deployments managed by the dsp operator in #729, we need to make sure that any users that have an existing kfdef referencing the current `data-science-pipelines` manifests are not blocked by an error in the odh-operator due to referencing a `kustomizeConfig` that no longer exists.  We'll only need to maintain this for one or two versions while we tell users to migrate to the dsp-operator manifest

You will need to ensure that the manifests and overlays will "no-op" for anyone that may have a kfdef with the existing data-science-pipelines `kustomizeConfig` below
```yaml
  - kustomizeConfig:
      overlays:
        - metadata-store-mariadb
        - ds-pipeline-ui
        - object-store-minio
        - default-configs
      repoRef:
        name: manifests
        path: data-science-pipelines
    name: data-science-pipelines
```

We did the same thing for odh-dashboard when we deprecated [odh-dashboard/overlays/authentication](https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/overlays/authentication/kustomization.yaml)

**Comment by LaVLaS** [comment]
/hold

Putting a hold on this until the 1.5 release branch is tagged

**Comment by LaVLaS** [comment]
/unhold

1.5 release branch has been created, this can merge without any issues

**Comment by DharmitD** [comment]
@LaVLaS @anishasthana @VaishnaviHire this PR is now ready to be merged, thanks.

**Review by LaVLaS — CHANGES_REQUESTED** [review]
@DharmitD You need need to remove `data-science-pipelines` from the tests [kfdef](https://github.com/opendatahub-io/odh-manifests/blob/master/tests/setup/odh-core.yaml#L56) so that CI tests will still work when this is merged.

**Comment by DharmitD** [comment]
> @DharmitD You need need to remove `data-science-pipelines` from the tests [kfdef](https://github.com/opendatahub-io/odh-manifests/blob/master/tests/setup/odh-core.yaml#L56) so that CI tests will still work when this is merged.

Done, updated to have  `data-science-pipelines` removed.

**Comment by DharmitD** [comment]
> @DharmitD This branch needs to be rebased with master

Done, rebased it with master.

**Comment by LaVLaS** [comment]
@VaishnaviHire Assuming there are no majors issues directly related to the removal of `data-science-pipelines` then I'll merge this if the 4.11 test fails

**Comment by VaishnaviHire** [comment]
This looks good. The tests for dashboard passed for both test clusters.

/lgtm

**Review by VaishnaviHire — APPROVED** [review]

**Pull request merged**
