### PR TITLE
Add machinesets and machine autoscalers to allow for gpu autoscaling

### PR DESCRIPTION
**Pull request by maroroman**
## Description
This PR is required for commit https://github.com/opendatahub-io/odh-dashboard/commit/2b3cdfda467789fcb604a9f7eefb0252204a5ec4 to work

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
/hold

This change does not affect the current version of odh-dashboard `v2.2.1` that is included in the odh 1.4.0 release

**Comment by LaVLaS** [comment]
@maroroman This change should be rolled into an update when odh-dashboard v2.4.0 is stable for release

**Comment by LaVLaS** [comment]
Closing this since it needs to be included in an update to odh-dashboard v2.4.0

**Pull request closed without merging**
