### PR TITLE
Update Cluster Monitoring rbac to account for deprecated APIs

### PR DESCRIPTION
**Pull request by anishasthana**
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Comment by crobby** [comment]
Do we need a jira for this?

**Review by crobby — COMMENTED** [review]
Looks good

**Comment by anishasthana** [comment]
https://issues.redhat.com/browse/ODH-549

**Comment by nakfour** [comment]
looks good, tested the scraping end points and seems to be working.
/lgtm

**Review by nakfour — APPROVED** [review]

**Pull request merged**
