### PR TITLE
Add Trino kustomize manifests

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Review by LaVLaS — CHANGES_REQUESTED** [review]
@rimolive This will need some basictests that we can include in CI runs to verify it is working as intended.

**Comment by nakfour** [comment]
@rimolive can you please add a description for what this PR is adding and how to test it

**Comment by anishasthana** [comment]
https://github.com/opendatahub-io/odh-manifests/pull/373 replaces this

**Pull request closed without merging**
