### PR TITLE
Use JH images in notebook controller tests

### PR DESCRIPTION
**Pull request by samuelvl**
Use the image streams provided by Jupyterhub to test the following images:

- `s2i-minimal-notebook:v0.3.0-py38`
- `s2i-generic-data-science-notebook:v0.0.5`

### CODE REVIEW

**Comment by LaVLaS** [comment]
/unhold

ODH v1.3 release has been tagged

**Comment by samuelvl** [comment]
@LaVLaS Ready to be reviewed :)

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by samuelvl** [comment]
Test are failing due to:

```
 SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 104.0.5112.79 with binary path /usr/bin/google-chrome 
```

**Pull request merged**
