### PR TITLE
Update JSP to 0.2.2, add secrets to the role

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by nakfour** [comment]
Tested this with creating a secret and it worked. /lgtm

**Review by nakfour — APPROVED** [review]

**Comment by crobby** [comment]
Possible real problem with the UI maybe:
ERROR:root:Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="variable_name"]"}
  (Session info: headless chrome=89.0.4389.90)
Traceback (most recent call last):
  File "/root/peak/operator-tests/odh-manifests/basictests/jupyterhub/jhtest.py", line 318, in <module>
    jhs.run()
  File "/root/peak/operator-tests/odh-manifests/basictests/jupyterhub/jhtest.py", line 171, in run
    raise e
  File "/root/peak/operator-tests/odh-manifests/basictests/jupyterhub/jhtest.py", line 155, in run
    self.spawn()
  File "/root/peak/operator-tests/odh-manifests/basictests/jupyterhub/jhtest.py", line 234, in spawn
    self.test_environment_variables()
  File "/root/peak/operator-tests/odh-manifests/basictests/jupyterhub/jhtest.py", line 195, in test_environment_variables
    self.add_environment_variable('foo', 'bar')
  File "/root/peak/operator-tests/odh-manifests/basictests/jupyterhub/jhtest.py", line 204, in add_environment_variable
    key_elem = self.driver.find_element(By.NAME, 'variable_name')
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="variable_name"]"}
  (Session info: headless chrome=89.0.4389.90)

**Comment by crobby** [comment]
Trying a rebase of this in PR https://github.com/opendatahub-io/odh-manifests/pull/363

**Comment by crobby** [comment]
It looks like the rebased version also fails.  My guess is that the new JH image has changed something in the UI and that is tripping the tests up.

**Comment by crobby** [comment]
@vpavlin @mroman-redhat 

Even after rebasing, I see the following error:
ERROR:root:Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="variable_name"]"}

When I look in the UI and hit the "add" button for adding env vars, I see the following.....
`<input class="KeyForm" name="" type="text" value="">`

I'm not super familiar with the jupyterhub selenium tests, but I think the empty value for the name is what's hurting the test....It's likely that either the test needs to be updated or the name shouldn't be empty (I don't think it should be empty either way).

**Comment by mroman-redhat** [comment]
@crobby I changed the way the IDs of the key and value elements are created so that there are no duplicate IDs, but I did not update the tests, so that is probably it.

**Comment by vpavlin** [comment]
FYI @mroman-redhat I have incorporated your commit for tests to this one

**Comment by vpavlin** [comment]
Closes #371

**Comment by crobby** [comment]
@vpavlin I'm going to close #363 since the rebase wasn't sufficient.

**Comment by vpavlin** [comment]
I ran the tests on my cluster and they passed (ok hit the cluster resource issue, but the specific issue from this PR did not manifest itself).

I limited JH test to only test the Spark image and I'll try to catch the cluster to look into what'S going on there

**Comment by vpavlin** [comment]
@crobby I have no idea why the last change helped, but the tests past - does it count?

**Pull request merged**
