### PR TITLE
Parameterize cuda build chain

### PR DESCRIPTION
**Pull request by vpavlin**
@LaVLaS

### CODE REVIEW

**Comment by LaVLaS** [comment]
Initial test with default value built the cuda images successfully for `10.1`. I will test tomorrow with a parameter for `10.2`

**Comment by LaVLaS** [comment]
Can we change the cuda notebook `requests` value to half of the limit for `cpu` and `memory`. This would provide user's some flexibility to start the builds if their available resources doesn't meet the limit.

**Comment by vpavlin** [comment]
> Can we change the cuda notebook `requests` value to half of the limit for `cpu` and `memory`. This would provide user's some flexibility to start the builds if their available resources doesn't meet the limit.

Done

**Pull request merged**
