### PR TITLE
Dashboard refactor

### PR DESCRIPTION
**Pull request by strangiato**
Refactored the `grafana/base` folder to better organize the dashboards from the various components and provide a better structure moving forward to add additional dashboards.

I have validated that `kustomize build grafana/grafana/base` results in the same YAML output as prior to the refactor so no functional changes should result from this PR.

### CODE REVIEW

**Review by anishasthana — CHANGES_REQUESTED** [review]
@strangiato thanks for the PR. Can you please clean up the commits on the PR?

**Comment by strangiato** [comment]
Thanks @anishasthana!  Hopefully that is a bit better.  Let me know if there is any additional cleanup needed.

**Comment by LaVLaS** [comment]
@tumido Will this require any updates in OperateFirst?

**Comment by hemajv** [comment]
> @tumido Will this require any updates in OperateFirst?

this lgtm! :+1: and will not require any updates on our end

**Review by tumido — COMMENTED** [review]
@LaVLaS as @hemajv said :slightly_smiling_face: No changes needed on our end.

Thank you for the heads up! :+1: :100:

/lgtm

**Comment by anishasthana** [comment]
@strangiato can you rebase on master? We recently had to update the tests to fix flaky ci.

**Comment by strangiato** [comment]
Done!

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
