### PR TITLE
Upgrade notebook-controller to v1.7.0-2 of odh/kubeflow

### PR DESCRIPTION
**Pull request by harshad16**
Upgrade notebook-controller to v1.7.0-2 of odh/kubeflow

## Description

The tag v1.7.0-2 of odh/kubeflow contains fixes.
Details available on release notes:
https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-2

Fixes: https://github.com/opendatahub-io/odh-dashboard/issues/1619

## How Has This Been Tested?

Deploy on an ODH cluster.
And execute a notebook to test this behaviour.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by harshad16** [comment]
Ready for Review and Merge.

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by harshad16** [comment]
The e2e tests are failing, as the odh-dashboard part of e2e, uses ods-ci for verifying the notebook workflow.
The ods-ci spins a notebook and goes over each login page to test the notebook out.
it is failing, as the notebook is updated with this tag v1.7.0-2 to have no more skip of oauth-proxy login page.
so traversing through the oauth-proxy login page needs to be included in ods-ci.
i will work on getting that bit in. 

For this current PR.
@LaVLaS  would you be inclined to get this merged and i can work on getting the ci issue resolved via another pr.
or would you suggest to get the ci fixed first.

the reason to get this merged, is as the notebook-controller previous version v1.7.0-1 would cause issue with odh-dashboard latest master

**Comment by LaVLaS** [comment]
@harshad16 We will need to resolve this test failure in this PR since their appears to be an issue around the test that verifies the functionality between dashboard and notebook-controller

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Pull request merged**
