### PR TITLE
Move modelmesh services monitors into the applications namespace

### PR DESCRIPTION
**Pull request by VannTen**
## Description
This simply moves modelmesh service monitor in the applications namespace instead of the monitoring namespace.
Since the monitoring namespace can in some scenarios (in that case, downstream usage by RHODS) be scrapped by a cluster-wide prometheus, this avoid that this cluster-wide prometheus would scrape itself, causing the issue discussed [here](https://issues.redhat.com/browse/RHODS-7570)

## How Has This Been Tested?
Deploying RHODS operator on an Openshift cluster.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by VannTen** [comment]
This is modifying some stuff which was introduced in #732 and is causing
the issue, btw.

**Comment by anishasthana** [comment]
cc @VedantMahabaleshwarkar

**Review by VedantMahabaleshwarkar — APPROVED** [review]

**Comment by VannTen** [comment]
I'm not sure what the failures are related to, does not seem to be related to this PR changes, right ?

**Comment by VaishnaviHire** [comment]
@VannTen This PR needs a rebase

**Comment by VannTen** [comment]
I still don't get the relation between the change and the tests failing. Are the e2e tests stable ?

**Comment by VannTen** [comment]
@VedantMahabaleshwarkar The rebase scraped the lgtm, if you can re-put it...

**Comment by Jooho** [comment]
@VannTen The Service Monitor can be deployed without prometheus? I means with the following kfdef can work ?
~~~
kind: KfDef
apiVersion: kfdef.apps.kubeflow.org/v1
metadata:
  name: opendatahub
  namespace: opendatahub
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - odh-model-controller
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/main'
~~~
If not, I think it is not a good idea to put this into model-mesh. we already have modelmesh-monitoring and this is the right place to have all manifests related to monitoring. This is the only way to solve your issue?

**Comment by VannTen** [comment]
/hold
(following dicussion with @Jooho )

**Comment by Jooho** [comment]
@jgarciao @VannTen and I discuss this and it would not be a good idea to put monitoring objects into model-mesh manifests because we have modelmesh-monitoring manifests. So we agree that we try to add the parameter "monitoring-namespace" into modelmesh-monitoring folder instead of moving this manifest file.

**Comment by VannTen** [comment]
@Jooho 
> ... it would not be a good idea to put monitoring objects into model-mesh manifests because we have modelmesh-monitoring manifests. 

Could you please put the rationale you explained to Vedant and me here so we don't repeat the same thing with something else in the future ?

**Comment by andrewballantyne** [comment]
We just merged https://github.com/opendatahub-io/odh-manifests/pull/826 -- I'm going to say you needed this fix and didn't have it during your e2e run -- let me retest.

/retest

**Comment by lucferbux** [comment]
Thanks @andrewballantyne I was writting exactly that, we found some issues in the CI, that are already addressed [here](https://github.com/opendatahub-io/odh-dashboard/pull/1256), hope this will fix the issue!

**Comment by Jooho** [comment]
@andrewballantyne @lucferbux Thanks for your help. My other PR passed all tests after rebasing. 
This PR might need to rebase codes.

**Comment by VannTen** [comment]
Hum, I'm not sure I'm following. Didn't you say we could not use the
approach in this PR ? Why rebasing it then, if we need to use another
way ?

**Comment by Jooho** [comment]
Just noticed that `ci/prow/odh-manifests-e2e` failed from this PR. So I guess there are some commits that from odh-manifests to fix the test. Actually, the test failed with the dashboard, not your changes.
My other PR had the same issue and was fixed after rebasing the latest commits.

**Comment by VannTen** [comment]
> Hum, I'm not sure I'm following. Didn't you say we could not use the approach in this PR ? Why rebasing it then, if we need to use another way ?

@Jooho

**Comment by Jooho** [comment]
oh I thought you changed the logic to use params from modelmesh-monitoring. 
Please use the param instead of moving the object into model-mesh directory.

**Pull request closed without merging**
