### PR TITLE
Fix tabbing in odh-notebook-controller docs

### PR DESCRIPTION
**Pull request by strangiato**
## Description
Fixed the indentation level for the example docs for odh-notebook-controller

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by strangiato** [comment]
@anishasthana any suggestions on the failing tests?  Since this change is just a README update it shouldn't change anything that impacts the tests.

**Comment by anishasthana** [comment]
Sometimes these tests are a little flakey...

/retest

**Comment by strangiato** [comment]
Looks like tests are passing after the rebase.

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by strangiato** [comment]
@LaVLaS can you readd the lgtm tag after the rebase?

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
