### PR TITLE
Create mysql overlays in kfp-tekton

### PR DESCRIPTION
**Pull request by rimolive**

### CODE REVIEW

**Comment by gmfrasca** [comment]
I think this looks good, but since we don't yet have the db replacement overlay and config in code yet we should probably also update the kfdef (`./kfdef/pipelines_prototype.yaml`) to include this overlay

**Review by gmfrasca — COMMENTED** [review]
/lgtm

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Review by DharmitD — APPROVED** [review]
/approve

**Pull request merged**
