### PR TITLE
First incubation of the dashboard with v2.14.0

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

First release of the incubation branch.

Also includes https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.14.0

### CODE REVIEW

**Comment by lucferbux** [comment]
@LaVLaS @VaishnaviHire @zdtsw Ok, this is the first incubation release.
I've copied all the manifest files from `incubation` as well ass the image we get out of nightly after merging the release with `incubation`.
Testing right now this in my cluster.

**Comment by lucferbux** [comment]
Ok, tested in a PSI cluster and it seems to be working fine, attaching the kfdef resource:

```yaml
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  creationTimestamp: '2023-08-04T09:09:48Z'
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
  generation: 1
  managedFields:
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:applications': {}
          'f:repos': {}
      manager: Mozilla
      operation: Update
      time: '2023-08-04T09:09:48Z'
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"kfdef-finalizer.kfdef.apps.kubeflow.org"': {}
      manager: manager
      operation: Update
      time: '2023-08-04T09:09:48Z'
    - apiVersion: kfdef.apps.kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2023-08-04T09:19:19Z'
  name: odh-dashboard
  namespace: opendatahub
  resourceVersion: '267873202'
  uid: 14d80434-341a-412a-b6c9-b0709f2717d6
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests-relase
          path: odh-dashboard
      name: odh-dashboard
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/master'
    - name: manifests-dashboard
      uri: 'https://github.com/opendatahub-io/odh-dashboard/tarball/main'
    - name: manifests-relase
      uri: >-
        https://github.com/lucferbux/odh-manifests/tarball/prepare-incubation-release
status:
  conditions:
    - lastUpdateTime: '2023-08-04T09:09:48Z'
      reason: Kubeflow Deployment completed
      status: 'True'
      type: Available
```

**Comment by lucferbux** [comment]
@LaVLaS I think trustyai/codeflare tests are failing

**Comment by LaVLaS** [comment]
/retest

To see if the codeflare, ray and trustyai issues are a fluke

**Comment by LaVLaS** [comment]
@lucferbux I deployed this locally to debug the issue and I think a recent change to https://github.com/project-codeflare/codeflare-sdk/pull/266 broke the codeflare CI tests

CC @Maxusmusti @anishasthana

**Comment by anishasthana** [comment]
I've opened https://github.com/opendatahub-io/odh-manifests/pull/910 which should help

**Comment by lucferbux** [comment]
@LaVLaS @anishasthana ok thanks, once that's merged I can rebase my PR!

**Comment by LaVLaS** [comment]
Admin merging this since the dashboard tests are running successfully in my local deployment & CI environment. We are still waiting on the CI test fix for Distributed Workloads in #910 to resolve the unrelated issues

**Pull request merged**
