### PR TITLE
Argo Server and Prometheus secure URLs in ODH Dashboard

### PR DESCRIPTION
**Pull request by eartvit**
Hello,
I propose a small change to the route YAML files for ArgoWF server and Prometheus so they have HTTPS URLs inside ODH Dashboard.
Best regards,
Arthur

### CODE REVIEW

**Comment by crobby** [comment]
Great, looks like the test is passing now.  Thanks.

**Review by anishasthana — CHANGES_REQUESTED** [review]
Hey @eartvit , can you squash the commits please!

**Comment by nakfour** [comment]
@eartvit @anishasthana any PR submitted must have an ODH issue opened and tracked in the sprint, does this have one?

**Pull request closed without merging**
