### PR TITLE
Add oauth proxy to ODH dashboard

### PR DESCRIPTION
**Pull request by accorvin**
This adds a basic OAuth Proxy sidecar container to the ODH Dashboard
pod. By default this will allow any authenticated user to access the
service. I expect downstream deployments to limit access by way of the
--openshift-sar argument. I additionally expect downstream deployments
to customize the value of the --cookie-secret argument.

### CODE REVIEW

**Comment by accorvin** [comment]
To test this:
1. Spin up an instance of the ODH using the following (or similar) KFDef:
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        overlays:
          - authentication
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
  repos:
    - name: manifests
      uri: 'https://github.com/accorvin/idh-manifests/tarball/add-dashboard-oauth'
  version: v0.9
```
2. Access the ODH Dashboard route - you should be prompted to log in with OpenShift auth
3. After successfully logging in, you should be able to see the ODH dashboard.

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Review by LaVLaS — CHANGES_REQUESTED** [review]
@accorvin Can you add a quick description in the README about this overlay and what it enables

**Comment by nakfour** [comment]
@accorvin also, are there test updates?

**Comment by LaVLaS** [comment]
The only test update would be required downstream where this overlay will be enabled

**Review by LaVLaS — APPROVED** [review]
/lgtm

**Comment by nakfour** [comment]
@LaVLaS I dont understand your statement, we added authentication for odh dashboard here, we need a test for it.

**Comment by LaVLaS** [comment]
@nakfour Authentication is user optional and not enabled in any of the ODH kfdefs so there is no upstream CI issue.  

This is being enabled and tested downstream where @accorvin has already offered to submit a PR to update those tests.  The test framework downstream will eventually be utilized/promoted upstream when development stabilizes.

**Comment by crobby** [comment]
/test all
slow mirror for oc client

**Comment by crobby** [comment]
Can't explain the test fail.  Nightlies all passed overnight.

**Comment by crobby** [comment]
/test all
this time thriftserver complained

**Pull request merged**
