### PR TITLE
Dashboard v2.9.2

### PR DESCRIPTION
**Pull request by andrewballantyne**
The last two releases of the Dashboard
- https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.9.2
- https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.9.1
- https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.9.0

### CODE REVIEW

**Comment by andrewballantyne** [comment]
It says prometheus service was not available? Going to retest to see if that passes... maybe an outage?

/retest

**Comment by andrewballantyne** [comment]
/retest

I have no idea what is happening with the test -- seems the e2e pod had issues? Are flakes common here? Retesting...

**Comment by LaVLaS** [comment]
/approve

| I have no idea what is happening with the test -- seems the e2e pod had issues? Are flakes common here? Retesting...

Flakes are common while odh-manifests code updates are in flux OR openshift-ci infrastructure issues

**Comment by VaishnaviHire** [comment]
@andrewballantyne PR probably needs a rebase

**Comment by LaVLaS** [comment]
@andrewballantyne Based on the `Application is not available` message in the ods-ci test run screenshots and the `CrashLoopBackOff` when I deploy locally, I think the v2.9.1 image is experiencing the intermittent issue from the previous v2.9.0 PR on the quay.io/opendatahub/odh-dashboard:v2.9.1 image

```
Defaulted container "odh-dashboard" out of: odh-dashboard, oauth-proxy

> ods-dashboard-backend@1.0.0 start
> NODE_ENV=production node ./dist/server.js --log=1 --registry=localhost:50051

npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /opt/app-root/src/.npm/_cacache/tmp/185f0205
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000690000:0 "/opt/app-root/src/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /opt/app-root/src/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

**Comment by LaVLaS** [comment]
/retest

Kicking off a new test to see if the errors due to pods crashes are intermittent across test runs

**Comment by VaishnaviHire** [comment]
@LaVLaS @andrewballantyne 

I tested `quay.io/opendatahub/odh-dashboard:main` and `quay.io/opendatahub/odh-dashboard:nightly` images and the Crashloop error doesn't happen in those. Is this specific to v2.9.1 tag ?

**Comment by andrewballantyne** [comment]
> @LaVLaS @andrewballantyne
> 
> I tested `quay.io/opendatahub/odh-dashboard:main` and `quay.io/opendatahub/odh-dashboard:nightly` images and the Crashloop error doesn't happen in those. Is this specific to v2.9.1 tag ?

Have you tested `quay.io/opendatahub/odh-dashboard:v2.9.1`? Because I'm not sure how this tag is uniquely broken. I imagine this is a CI infra problem with our image (or something like that).

**Comment by VaishnaviHire** [comment]
> > @LaVLaS @andrewballantyne
> > I tested `quay.io/opendatahub/odh-dashboard:main` and `quay.io/opendatahub/odh-dashboard:nightly` images and the Crashloop error doesn't happen in those. Is this specific to v2.9.1 tag ?
> 
> Have you tested `quay.io/opendatahub/odh-dashboard:v2.9.1`? Because I'm not sure how this tag is uniquely broken. I imagine this is a CI infra problem with our image (or something like that).

Yeah tested v2.9.1 on my development cluster , it throws above mentioned error.

**Comment by LaVLaS** [comment]
> > @LaVLaS @andrewballantyne
> > I tested `quay.io/opendatahub/odh-dashboard:main` and `quay.io/opendatahub/odh-dashboard:nightly` images and the Crashloop error doesn't happen in those. Is this specific to v2.9.1 tag ?
> 
> Have you tested `quay.io/opendatahub/odh-dashboard:v2.9.1`? Because I'm not sure how this tag is uniquely broken. I imagine this is a CI infra problem with our image (or something like that).

Yes. CI runs will deploy ODH based on the HEAD commit of your PR branch.  In this case it will deploy the `odh-dashboard:v2.9.1` image you specified.  

The npm error I referenced below was from deploying your PR in my dev environment. Doing some manual deployments of images from `odh-dashboard:v2.9.1` up to `odh-dashboard:main-a998de8` result in the same error but the latest build, `main-883315d`, appears to run without any errors from my initial testing

**Comment by andrewballantyne** [comment]
> > > @LaVLaS @andrewballantyne
> > > I tested `quay.io/opendatahub/odh-dashboard:main` and `quay.io/opendatahub/odh-dashboard:nightly` images and the Crashloop error doesn't happen in those. Is this specific to v2.9.1 tag ?
> > 
> > 
> > Have you tested `quay.io/opendatahub/odh-dashboard:v2.9.1`? Because I'm not sure how this tag is uniquely broken. I imagine this is a CI infra problem with our image (or something like that).
> 
> Yeah tested v2.9.1 on my development cluster , it throws above mentioned error.

For my future knowledge (and likely to update the release steps of the Dashboard) how did you test the v2.9.1 image?

**Comment by VaishnaviHire** [comment]
> > 
> > Yeah tested v2.9.1 on my development cluster , it throws above mentioned error.
> 
> For my future knowledge (and likely to update the release steps of the Dashboard) how did you test the v2.9.1 image?

I created [odh-core](https://github.com/andrewballantyne/odh-manifests/blob/dashboard-2.9.1-release/kfdef/odh-core.yaml) KfDef and updated the [uri](https://github.com/andrewballantyne/odh-manifests/blob/dashboard-2.9.1-release/kfdef/odh-core.yaml#L67) field to point to your PR branch - `https://github.com/andrewballantyne/odh-manifests/tarball/dashboard-2.9.1-release` .  This will deploy manifests changes from the PR

**Comment by LaVLaS** [comment]
For odh-dashboard, you can use the `make deploy` command from the [odh-dashboard](https://github.com/opendatahub-io/odh-dashboard/blob/main/CONTRIBUTING.md#deploying-your-image) repo since the manifests should be the same.  To specify an image different from the default, you can use the command below

```
make deploy -e IMAGE_REPOSITORY=<IMAGE URL>
```

**Comment by andrewballantyne** [comment]
Image may not be deployed when this started -- we'll need to likely retest once the image is on quay.

**Comment by VaishnaviHire** [comment]
Looks like infrastructure issue

/test odh-manifests-e2e

**Review by VaishnaviHire — COMMENTED** [review]
/lgtm

**Comment by LaVLaS** [comment]
/retest

Final retest before a force merge with passing dashboard test

**Pull request merged**
