### PR TITLE
Use test framework to use opendatahub-io/peak repo for testing

### PR DESCRIPTION
**Pull request by LaVLaS**
## Description
Updates the peak test framework to pull from repos under the opendatahub-io instead of references to user forks and other deprecated github organizations

## How Has This Been Tested?
I built and deployed the test container locally then run the CI tests without any errors

## Merge criteria:
Existing CI tests run without any issues

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by anishasthana** [comment]
@harshad16 @DharmitD this may be relevant to you folks too

**Review by harshad16 — COMMENTED** [review]
/lgtm :+1: 

Thanks , i will pull this in dspo repo, as we use peak there as well.

**Review by DharmitD — COMMENTED** [review]
/lgtm

**Comment by LaVLaS** [comment]
/approve

Merging this since it just adds local repos that ODH controls in the event we need to update the dependent frameworks

**Pull request merged**
