### PR TITLE
Use Postgres image from registry.rh.io to avoid breakage when OpenShift removes older versions

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by vpavlin** [comment]
@crobby Seems like Strimzi has issues on 4.6?

**Comment by crobby** [comment]
@vpavlin This test isn't on 4.6 yet...we can't merge that until this PR merges

**Comment by crobby** [comment]
@vpavlin:  Nightly builds are also failing with similar (the same probably) Kafka problems.  I'd be ok merging this one as it does address the issue we're having with 4.6.

**Pull request merged**
