### PR TITLE
Update dashboard files

### PR DESCRIPTION
**Pull request by lucferbux**
Update dashboard files:
* Opendatahub CRD
* Role
* Clusterrole
* Clusterrolebinding

### CODE REVIEW

**Comment by LaVLaS** [comment]
/hold

Putting this on hold until after #588 is merged for the ODH 1.3 release

**Comment by lucferbux** [comment]
@LaVLaS @samuelvl I've rebased #588 and added the permissions for the groups admin panel and also the latest changes in the `manifest` folder in odh, I think these changes are targeted for the GPU permissions.

**Comment by samuelvl** [comment]
@lucferbux For local testing and development we are using the [odh-dashboard/manifests](https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests ) folder. I think we should only update `odh-manifests` when there is a new release in the odh-dashboard repository.

What do you think @LaVLaS ? Is there any release planned for the dashboard to include the notebook controller UI? We could use this PR for that.

**Comment by lucferbux** [comment]
> @lucferbux For local testing and development we are using the [odh-dashboard/manifests](https://github.com/opendatahub-io/odh-dashboard/tree/main/manifests) folder. I think we should only update `odh-manifests` when there is a new release in the odh-dashboard repository.
> 
> What do you think @LaVLaS ? Is there any release planned for the dashboard to include the notebook controller UI? We could use this PR for that.

@samuelvl Ok great, should I keep this open? Cause it would be needed once the groups panel is implemented in the dashboard, do we have any way to keep track for everything or just copying the manifest folder once we have a new release?

**Comment by LaVLaS** [comment]
I agree with @samuelvl. Since the manifests in the `odh-dashboard` repo can be referenced for local development, any updates to `odh-manifeests/odh-dashboard` should be packaged with the odh-dashboard container image that it affects.  Currently, odh-manifests is deploying `odh-dashboard:v2.0` so these changes do not affect any features that are in that image.

**Comment by samuelvl** [comment]
@lucferbux @LaVLaS Thanks for the clarification, I'm closing this PR until there is a new release of ODH dashboard

**Pull request closed without merging**
