### PR TITLE
Update Notebook Controller Role

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by LaVLaS** [comment]
@VaishnaviHire Will this require an update to the kf-notebook-controller image that is creating `NetworkPolicies` for the `Notebook` CRs?

**Comment by VaishnaviHire** [comment]
> @VaishnaviHire Will this require an update to the kf-notebook-controller image that is creating `NetworkPolicies` for the `Notebook` CRs?

I think we can hold this, until we have the  https://github.com/opendatahub-io/kubeflow/pull/65 PR merged. Once its merged I will update the image in this PR.

/hold

**Comment by LaVLaS** [comment]
Closing this since the changes are included in #759

**Comment by shalberd** [comment]
Cool, thank you, proxy and networkpolicy support now in community ODH, too.

**Pull request closed without merging**
